### ISSUE TITLE
.flat is not a function

### ISSUE THREAD

**Issue by dac3971** [mediocre/bloodhound#18]
Can anyone help with this error?
`Process crashed with: TypeError: packageInfo.map(...).flat is not a function
    at /home/runner/node_modules/@mediocre/bloodhound/carriers/ups.js:129:85
    at args (/home/runner/node_modules/async/dist/async.js:3815:21)
    at Request._callback (/home/runner/node_modules/@mediocre/bloodhound/carriers/ups.js:104:17)
    at Request.self.callback (/home/runner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/runner/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/runner/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by freshlogic** [comment]
Hey @dac3971. You’ll need to use a version of Node that supports Array.flat(). We’re mostly using Node v12 but looks like it’s also supported back in v11.6 https://thecodebarbarian.com/whats-new-in-es2019-flat-flatmap-catch.html
